package imagekit

import "github.com/imagekit-developer/imagekit-go/v2/shared"

// Backwards-compatible type aliases for types consolidated into the shared package.

type FileAITag = shared.AITag
type FileSelectedFieldsSchema = shared.SelectedFieldsSchemaItem
type FileSelectedFieldsSchemaDefaultValueUnion = shared.SelectedFieldsSchemaItemDefaultValueUnion
type FileSelectedFieldsSchemaDefaultValueMixedItemUnion = shared.SelectedFieldsSchemaItemDefaultValueMixedItemUnion
type FileSelectedFieldsSchemaMaxValueUnion = shared.SelectedFieldsSchemaItemMaxValueUnion
type FileSelectedFieldsSchemaMinValueUnion = shared.SelectedFieldsSchemaItemMinValueUnion
type FileSelectedFieldsSchemaSelectOptionUnion = shared.SelectedFieldsSchemaItemSelectOptionUnion
type FileVersionInfo = shared.VersionInfo

type FileUploadResponseAITag = shared.AITag
type FileUploadResponseSelectedFieldsSchema = shared.SelectedFieldsSchemaItem
type FileUploadResponseSelectedFieldsSchemaDefaultValueUnion = shared.SelectedFieldsSchemaItemDefaultValueUnion
type FileUploadResponseSelectedFieldsSchemaDefaultValueMixedItemUnion = shared.SelectedFieldsSchemaItemDefaultValueMixedItemUnion
type FileUploadResponseSelectedFieldsSchemaMaxValueUnion = shared.SelectedFieldsSchemaItemMaxValueUnion
type FileUploadResponseSelectedFieldsSchemaMinValueUnion = shared.SelectedFieldsSchemaItemMinValueUnion
type FileUploadResponseSelectedFieldsSchemaSelectOptionUnion = shared.SelectedFieldsSchemaItemSelectOptionUnion
type FileUploadResponseVersionInfo = shared.VersionInfo

type BetaV2FileUploadResponseAITag = shared.AITag
type BetaV2FileUploadResponseSelectedFieldsSchema = shared.SelectedFieldsSchemaItem
type BetaV2FileUploadResponseSelectedFieldsSchemaDefaultValueUnion = shared.SelectedFieldsSchemaItemDefaultValueUnion
type BetaV2FileUploadResponseSelectedFieldsSchemaDefaultValueMixedItemUnion = shared.SelectedFieldsSchemaItemDefaultValueMixedItemUnion
type BetaV2FileUploadResponseSelectedFieldsSchemaMaxValueUnion = shared.SelectedFieldsSchemaItemMaxValueUnion
type BetaV2FileUploadResponseSelectedFieldsSchemaMinValueUnion = shared.SelectedFieldsSchemaItemMinValueUnion
type BetaV2FileUploadResponseSelectedFieldsSchemaSelectOptionUnion = shared.SelectedFieldsSchemaItemSelectOptionUnion
type BetaV2FileUploadResponseVersionInfo = shared.VersionInfo

type UploadPreTransformSuccessEventDataAITag = shared.AITag
type UploadPreTransformSuccessEventDataSelectedFieldsSchema = shared.SelectedFieldsSchemaItem
type UploadPreTransformSuccessEventDataSelectedFieldsSchemaDefaultValueUnion = shared.SelectedFieldsSchemaItemDefaultValueUnion
type UploadPreTransformSuccessEventDataSelectedFieldsSchemaDefaultValueMixedItemUnion = shared.SelectedFieldsSchemaItemDefaultValueMixedItemUnion
type UploadPreTransformSuccessEventDataSelectedFieldsSchemaMaxValueUnion = shared.SelectedFieldsSchemaItemMaxValueUnion
type UploadPreTransformSuccessEventDataSelectedFieldsSchemaMinValueUnion = shared.SelectedFieldsSchemaItemMinValueUnion
type UploadPreTransformSuccessEventDataSelectedFieldsSchemaSelectOptionUnion = shared.SelectedFieldsSchemaItemSelectOptionUnion
type UploadPreTransformSuccessEventDataVersionInfo = shared.VersionInfo
